#!/usr/bin/env bash

if [ "$#" -eq 0 ]
then
    echo -n "URL: "
    read url
else
    url="$1"
fi

cd "$(mktemp -d -t play-video-url_XXXXX)"

python3.13 -m yt_dlp "$url" -o "out.%(ext)s" --exec "vlc {}"

rm out.*
